# Generated by Django 5.0 on 2023-12-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_user_alter_employee_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
