# Generated by Django 5.0 on 2023-12-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employee_user'),
    ]

    operations = [
    ]
