# Generated by Django 5.0 on 2023-12-27 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productinshop_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('products', models.ManyToManyField(through='api.SellProduct', to='api.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sale'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sale'),
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
