# Generated by Django 5.0 on 2023-12-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sale_alter_salepayment_sale_alter_sellproduct_sell_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='Saleing_price',
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('Sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='api.SaleProduct', to='api.product'),
        ),
        migrations.DeleteModel(
            name='SellProduct',
        ),
    ]
