# Generated by Django 5.0 on 2023-12-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_selling_price_product_saleing_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='Sale',
            new_name='sale',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='amountPaid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productinshop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
