# Generated by Django 5.0 on 2023-12-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_sale_saleproduct_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='api.sale'),
        ),
    ]
