# Generated by Django 5.0 on 2023-12-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shop_is_master_alter_saleproduct_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Saleing_price',
            new_name='selling_price',
        ),
    ]
