# Generated by Django 5.0 on 2023-12-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_saleing_price_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='Saleing_price',
        ),
    ]
