# Generated by Django 5.0 on 2023-12-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_selling_price_product_saleing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Saleing_price',
            new_name='saleing_price',
        ),
    ]
