# Generated by Django 5.0 on 2023-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_saleing_price_product_saleing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amountPaidToSupplier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
