# Generated by Django 5.0 on 2023-12-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_purchase_amountpaidtosupplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferitem',
            name='product_in_shop',
        ),
        migrations.AddField(
            model_name='transferitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
